// <auto-generated />
namespace KisiselBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userstats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userstats));
        
        string IMigrationMetadata.Id
        {
            get { return "201808022112427_user-stats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
