// <auto-generated />
namespace KisiselBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commentdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commentdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201807182136556_comment-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
